# coding: utf-8
# pyright: basic

"""Syzygy tables from 3 to 5 pieces: what to download, from where, and how to open them.

The manifest (`syzygy_manifest.json`, generated by `tools/build_syzygy_manifest.py`)
lists the 290 files of the Lichess mirror with size and SHA-256. The download
proceeds file by file: one already on disk with the right size is skipped,
so cancelling and resuming picks up where it left off; each file is checked
against its hash before taking its final name. The tables live in the user's
data directory (`syzygy/`), outside the add-on folder, which gets wiped on
every update.

No NVDA here: the tests download nothing and open 3-piece tables that ship
in the repository.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Iterable

from ..paths import import_bundled
from ..tactic.db import ADDON_DATA_DIRECTORY
from ..tactic.download import CHUNK, USER_AGENT, DownloadCancelled, DownloadError, ProgressCallback

with import_bundled():
	import chess
	import chess.syzygy


MANIFEST_PATH = Path(__file__).resolve().parent / "syzygy_manifest.json"
SYZYGY_DIRECTORY = ADDON_DATA_DIRECTORY / "syzygy"
# How many pieces the tables cover, at most. Above this, the judge stays silent.
MAX_PIECES = 5


@dataclasses.dataclass(frozen=True)
class TableFile:
	file: str
	kind: str  # "wdl" or "dtz"
	pieces: int
	bytes: int
	sha256: str
	url: str


@dataclasses.dataclass(frozen=True)
class TableSet:
	"""A set the user can choose to download: up to N pieces."""

	set_id: str
	max_pieces: int
	files: tuple[TableFile, ...]

	@property
	def total_bytes(self) -> int:
		return sum(f.bytes for f in self.files)


def load_manifest(path: Path = MANIFEST_PATH) -> tuple[TableFile, ...]:
	payload = json.loads(Path(path).read_text(encoding="utf-8"))
	return tuple(
		TableFile(
			file=str(entry["file"]),
			kind=str(entry["kind"]),
			pieces=int(entry["pieces"]),
			bytes=int(entry["bytes"]),
			sha256=str(entry["sha256"]),
			url=str(entry["url"]),
		)
		for entry in payload.get("files", [])
	)


def table_sets(files: Iterable[TableFile] | None = None) -> tuple[TableSet, ...]:
	"""The two sets offered: up to 4 pieces (a few MB) and up to 5 (almost 1 GB)."""
	files = tuple(files if files is not None else load_manifest())
	return tuple(
		TableSet(
			set_id=f"upTo{limit}",
			max_pieces=limit,
			files=tuple(f for f in files if f.pieces <= limit),
		)
		for limit in (4, 5)
	)


# ---------------------------------------------------------------- installed


def is_installed(table: TableFile, directory: Path = SYZYGY_DIRECTORY) -> bool:
	"""Present with the size from the manifest. The hash was checked at download time."""
	path = Path(directory) / table.file
	try:
		return path.stat().st_size == table.bytes
	except OSError:
		return False


def missing_files(files: Iterable[TableFile], directory: Path = SYZYGY_DIRECTORY) -> tuple[TableFile, ...]:
	return tuple(f for f in files if not is_installed(f, directory))


def installed_piece_limit(
	files: Iterable[TableFile] | None = None,
	directory: Path = SYZYGY_DIRECTORY,
) -> int:
	"""How many pieces the installed tables fully cover: 0, 3, 4 or 5."""
	files = tuple(files if files is not None else load_manifest())
	limit = 0
	for pieces in (3, 4, 5):
		group = [f for f in files if f.pieces == pieces]
		if group and all(is_installed(f, directory) for f in group):
			limit = pieces
		else:
			break
	return limit


# ---------------------------------------------------------------- download


def download_tables(
	files: Iterable[TableFile],
	directory: Path = SYZYGY_DIRECTORY,
	progress: ProgressCallback | None = None,
	cancel: threading.Event | None = None,
	timeout: float = 60.0,
	attempts_per_file: int = 3,
	retry_delay: float = 5.0,
) -> int:
	"""Download whatever is missing from `files` into `directory`; return how many files were downloaded.

	Progress counts the bytes of the whole set, with the already-installed
	ones added up front, so the progress bar resumes where it left off. A
	file that fails (network, size or hash) is retried on its own; after
	`attempts_per_file` tries the whole download stops with `DownloadError`.
	"""
	files = tuple(files)
	directory = Path(directory)
	directory.mkdir(parents=True, exist_ok=True)
	total = sum(f.bytes for f in files)
	done = sum(f.bytes for f in files if is_installed(f, directory))
	if progress:
		progress(done, total)
	downloaded = 0
	for table in files:
		if is_installed(table, directory):
			continue
		for attempt in range(1, attempts_per_file + 1):
			try:
				_download_file(table, directory, done, total, progress, cancel, timeout)
				break
			except (_FileFailed, urllib.error.URLError, OSError) as error:
				if attempt == attempts_per_file:
					raise DownloadError(f"download: {table.file}: {error}") from error
				if cancel is not None and cancel.wait(retry_delay):
					raise DownloadCancelled()
				elif cancel is None:
					time.sleep(retry_delay)
		done += table.bytes
		downloaded += 1
		if progress:
			progress(done, total)
	return downloaded


class _FileFailed(Exception):
	"""Arrived with a size or hash different from the manifest; worth retrying."""


def _download_file(
	table: TableFile,
	directory: Path,
	done_before: int,
	total: int,
	progress: ProgressCallback | None,
	cancel: threading.Event | None,
	timeout: float,
) -> None:
	partial = directory / (table.file + ".part")
	request = urllib.request.Request(table.url, headers={"User-Agent": USER_AGENT})
	digest = hashlib.sha256()
	received = 0
	try:
		with urllib.request.urlopen(request, timeout=timeout) as response, partial.open("wb") as out:
			while True:
				if cancel is not None and cancel.is_set():
					raise DownloadCancelled()
				chunk = response.read(CHUNK)
				if not chunk:
					break
				digest.update(chunk)
				out.write(chunk)
				received += len(chunk)
				if progress:
					progress(done_before + received, total)
		if received != table.bytes:
			raise _FileFailed(f"expected {table.bytes} bytes, received {received}")
		if digest.hexdigest() != table.sha256:
			raise _FileFailed("checksum mismatch")
		partial.replace(directory / table.file)
	except BaseException:
		partial.unlink(missing_ok=True)
		raise


# ---------------------------------------------------------------- open


def open_tablebase(directory: Path = SYZYGY_DIRECTORY) -> "chess.syzygy.Tablebase | None":
	"""Open whatever is in the folder; None if there is no table at all.

	Opening only registers the files; nothing is read until the first query,
	and a position whose material has no table raises `MissingTableError` right then.
	"""
	directory = Path(directory)
	if not directory.is_dir() or not any(directory.glob("*.rtb[wz]")):
		return None
	return chess.syzygy.open_tablebase(str(directory))
