# This file is covered by the GNU General Public License.
# See the file COPYING.txt for more details.

"""`tools/verify_puzzles.py`: does the manifest describe the files beside it?

The failure this guards against: the light database of September 2026 was
published with a manifest generated by a later build, so every file was the
right size and none had the right hash, and the add-on refused the download
without ever saying why.
"""

import gzip
import hashlib
import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS = Path(__file__).resolve().parents[3] / "tools"
_spec = importlib.util.spec_from_file_location("verify_puzzles", TOOLS / "verify_puzzles.py")
assert _spec is not None and _spec.loader is not None
verify_puzzles = importlib.util.module_from_spec(_spec)
sys.modules["verify_puzzles"] = verify_puzzles
_spec.loader.exec_module(verify_puzzles)


def _sha256(data: bytes) -> str:
	return hashlib.sha256(data).hexdigest()


class TestVerifyLocal(unittest.TestCase):
	def setUp(self):
		self.tmp = tempfile.TemporaryDirectory()
		self.addCleanup(self.tmp.cleanup)
		self.out = Path(self.tmp.name)
		self.db = b"a tiny database" * 100
		self.gz = gzip.compress(self.db)
		(self.out / "puzzles-light.db").write_bytes(self.db)
		(self.out / "puzzles-light.db.gz").write_bytes(self.gz)

	def _write_manifest(self, **overrides):
		manifest = {
			"schemaVersion": 2,
			"tiers": {
				"light": {
					"tier": "light",
					"puzzleCount": 3,
					"file": "puzzles-light.db",
					"bytes": len(self.db),
					"sha256": _sha256(self.db),
					"download": {
						"file": "puzzles-light.db.gz",
						"bytes": len(self.gz),
						"sha256": _sha256(self.gz),
						"parts": [
							{
								"file": "puzzles-light.db.gz",
								"bytes": len(self.gz),
								"sha256": _sha256(self.gz),
							},
						],
					},
				},
			},
		}
		manifest["tiers"]["light"].update(overrides)
		(self.out / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

	def test_a_manifest_that_matches_its_files_has_nothing_to_say(self):
		self._write_manifest()
		self.assertEqual(verify_puzzles.verify_local(self.out), [])

	def test_a_hash_from_another_build_is_caught(self):
		# What actually happened: same size, different bytes.
		other_build = bytes(self.gz[:-1]) + bytes([self.gz[-1] ^ 0xFF])
		self.assertEqual(len(other_build), len(self.gz))
		download = {
			"file": "puzzles-light.db.gz",
			"bytes": len(self.gz),
			"sha256": _sha256(other_build),
			"parts": [
				{"file": "puzzles-light.db.gz", "bytes": len(self.gz), "sha256": _sha256(other_build)},
			],
		}
		self._write_manifest(download=download)
		complaints = verify_puzzles.verify_local(self.out)
		self.assertEqual(len(complaints), 1)
		self.assertIn("puzzles-light.db.gz", complaints[0])
		self.assertIn("sha256", complaints[0])

	def test_a_file_the_manifest_names_but_nobody_built_is_caught(self):
		self._write_manifest()
		(self.out / "puzzles-light.db.gz").unlink()
		complaints = verify_puzzles.verify_local(self.out)
		self.assertEqual(len(complaints), 1)
		self.assertIn("missing", complaints[0])

	def test_a_wrong_size_is_named_as_a_size(self):
		self._write_manifest()
		(self.out / "puzzles-light.db").write_bytes(self.db + b"!")
		complaints = verify_puzzles.verify_local(self.out)
		self.assertEqual(len(complaints), 1)
		self.assertIn("bytes", complaints[0])


class TestExpectedFiles(unittest.TestCase):
	def test_a_split_archive_lists_the_parts_and_not_the_whole(self):
		manifest = {
			"tiers": {
				"full": {
					"file": "puzzles-full.db",
					"bytes": 10,
					"sha256": "x",
					"download": {
						"file": "puzzles-full.db.gz",
						"bytes": 6,
						"sha256": "y",
						"parts": [
							{"file": "puzzles-full.db.gz.part1", "bytes": 3, "sha256": "a"},
							{"file": "puzzles-full.db.gz.part2", "bytes": 3, "sha256": "b"},
						],
					},
				},
			},
		}
		names = [e.file for e in verify_puzzles.expected_files(manifest, include_databases=False)]
		self.assertEqual(names, ["puzzles-full.db.gz.part1", "puzzles-full.db.gz.part2"])

	def test_the_database_itself_is_only_expected_locally(self):
		manifest = {
			"tiers": {
				"light": {
					"file": "puzzles-light.db",
					"bytes": 10,
					"sha256": "x",
					"download": {
						"file": "puzzles-light.db.gz",
						"bytes": 6,
						"sha256": "y",
						"parts": [{"file": "puzzles-light.db.gz", "bytes": 6, "sha256": "y"}],
					},
				},
			},
		}
		local = [e.file for e in verify_puzzles.expected_files(manifest, include_databases=True)]
		published = [e.file for e in verify_puzzles.expected_files(manifest, include_databases=False)]
		self.assertEqual(local, ["puzzles-light.db", "puzzles-light.db.gz"])
		self.assertEqual(published, ["puzzles-light.db.gz"])
